### ISSUE TITLE
spr  header

### ISSUE THREAD

**Issue by iperov** [shlainn/game-file-formats#2]
0x00 uint16        unk1      Unknown <- looks like minus offset for centering sprite
0x02 uint16        unk2      Unknown
0x04 uint16        width     Sprite width in pixels
0x06 uint16        height    Sprite height in pixels

**Comment by shlainn** [comment]
Hmm, interesting idea. Time to dust off the ancient code I wrote back then to extract the archives...

**Comment by RyanfaeScotland** [comment]
Yay, more info! Would love to see this fixed but got zero time to work on it ever.

**Comment by shlainn** [comment]
I looked at the SPRs again and @iperov seems to be correct about it. I'll update the wiki page and close this issue

**Comment by iperov** [comment]
wow that was 6 years ago. How fast time goes by.

**Comment by RyanfaeScotland** [comment]
It does that, how different a world it was back then.

Great to see everyone still around though.
