### ISSUE TITLE
Encoding Problem with TEXT files

### ISSUE THREAD

**Issue by WizzardMaker** [shlainn/game-file-formats#4]
It seems like some of the constants might be wrong, because when I for example decode the .GER file with the "formula" in the wiki, I only get gibberish...
![image](https://user-images.githubusercontent.com/7768485/27254493-add92d3a-5389-11e7-82fe-385dd433757c.png)

How is the data ordered in those files? Plain text, or sorted data?

BTW GREAT source of information!

**Comment by WizzardMaker** [comment]
It looks like the files seem to have a ~2346 byte header
All Files start with the same sequence

The first word (starting at 2495, going to 2508) seems to be the same in English as in American.

**Comment by RyanfaeScotland** [comment]
Not sure how much this is being worked on these days WizzardMaker but thanks for the additional info!

**Comment by WizzardMaker** [comment]
Well, I am making an open source remake of Constructor (like CorsixTH) and those files would be really helpful. Do you know how the author came up with the decryption?

**Comment by shlainn** [comment]
I have no idea where the original pseudocode came from, but it is obviously wrong. After a surprisingly short bit of brute forcing, I arrived at the following correct parameters for decrypting the text files:

```
        counter = 171
        operand = 0
        for each byte:
            byte += counter
            byte ^= 58
            byte += (131 - operand)
            operand = byte
            counter += 1
        }
```
Tested on the GOG.com version, seems fine to me.

The header observed by WizzardMaker is actually a block of instructions for the translators ;)

**Comment by shlainn** [comment]
A neat trick I found to save a lot of effort in determining the parameters of this decryption (should this ever be necessary again) is to check if after the decryption of any byte the byte value is still in the ASCII range (< 128). If it isn't, abort this attempt and try different parameters.

**Comment by shlainn** [comment]
Another interesting observation, which is sort of obvious in hindsight: In addition to the 171 / 58 / 131 combination described above, there are other combinations of parameters that work (thanks, brute force):

- 107 186 67
- 171 186 3
- 107 58 195
- 235 58 67
- and certainly more.
